const menuToggle = document.getElementById("menuToggle");
const siteNav = document.getElementById("siteNav");
const langButtons = document.querySelectorAll(".lang-button");

const translations = {
  en: {
    brandTitle: "Rahmat Quran Classes",
    brandSubtitle: "Online Quran Learning With Adab and Care",
    navAbout: "About",
    navPrograms: "Programs",
    navTimings: "Timings",
    navFaq: "FAQ",
    navContact: "Contact",
    heroEyebrow: "Bismillah ir-Rahman ir-Rahim",
    heroTitle: "Online Quran learning with discipline, warmth, and daily progress.",
    heroText:
      "Rahmat Quran Classes is a calm, respectful place where students learn Quran, Quran Nazra, Para, Duas and Kalmas, and Urdu in a focused and encouraging environment.",
    heroForm: "Fill Contact Form",
    heroJoin: "Join a Session",
    heroSubjects: "See Subjects",
    badgeMorning: "Morning Batch",
    badgeEvening: "Evening Batch",
    badgeOnline: "Online Classes",
    heroPoint1: "Simple teaching with strong daily routine",
    heroPoint2: "Same subjects taught in both sessions",
    heroPoint3: "Designed for online students and families",
    panelLabel: "Admissions Open",
    panelTitle: "Five essential subjects in one clear learning path.",
    subject1: "Quran",
    subject2: "Quran Nazra",
    subject3: "Para",
    subject4: "Duas and Kalmas",
    subject5: "Urdu",
    miniMorning: "Morning",
    miniEvening: "Evening",
    miniMode: "Mode",
    miniModeValue: "Online Classes",
    miniContact: "Contact",
    aboutEyebrow: "About The Classes",
    aboutTitle: "Made for families who want sincere and reliable online Quran classes.",
    aboutText:
      "Rahmat Quran Classes focuses on daily consistency, respectful teaching, and a steady learning method that helps students improve comfortably without pressure or confusion.",
    aboutFeatureTitle: "A focused routine for real improvement",
    aboutFeatureText:
      "Each session is designed to help students build reading habits, strengthen Quran connection, remember important duas and kalmas, and improve confidence in a way that feels calm and manageable.",
    aboutCard1Title: "Respectful Teaching",
    aboutCard1Text: "Students are guided with patience, correction, and clear explanation.",
    aboutCard2Title: "Strong Routine",
    aboutCard2Text: "Regular practice helps children stay connected to learning every day.",
    aboutCard3Title: "Simple Method",
    aboutCard3Text: "Lessons stay easy to follow, even for beginners or younger students.",
    aboutCard4Title: "Family Friendly",
    aboutCard4Text: "Batch timings are arranged to be practical for home, school, and especially online study schedules.",
    teacherEyebrow: "Teacher Profile",
    teacherTitle: "Nazim teaches with patience, clarity, and a strong daily learning routine.",
    teacherText:
      "This profile introduces Nazim in a respectful and professional way for families who want to know more about the teacher behind the classes.",
    teacherLabel: "Teacher Name",
    teacherMainText:
      "Nazim guides students with a calm and focused teaching style that helps them improve steadily. The aim is to build confidence, regularity, and meaningful progress in Quran learning through simple explanation and personal attention.",
    teacherCard1Title: "Teaching Style",
    teacherCard1Text:
      "Nazim teaches with patience, clear guidance, repetition, and a gentle correction method that makes learning comfortable.",
    teacherCard2Title: "Subjects Taught",
    teacherCard2Text:
      "Quran, Quran Nazra, Para, Duas and Kalmas, and Urdu are taught in a simple and student-friendly structure.",
    teacherCard3Title: "Class Approach",
    teacherCard3Text:
      "The classes focus on daily routine, reading improvement, good manners, and helping students stay connected to Islamic learning.",
    teacherCard4Title: "For Families",
    teacherCard4Text:
      "Suitable for parents looking for a respectful online class with regular timings and a steady teaching method.",
    stat1Label: "Subjects",
    stat1Text: "Quran, Quran Nazra, Para, Duas and Kalmas, and Urdu",
    stat2Label: "Daily Sessions",
    stat2Text: "One morning session and one evening session built for online learners",
    stat3Label: "Session Time",
    stat3Text: "Focused classes with a clean and manageable learning window",
    programsEyebrow: "Programs",
    programsTitle: "A simple curriculum that covers what families care about most.",
    program1Title: "Quran",
    program1Text:
      "Core Quran learning that helps students stay connected with daily recitation, listening, and a stronger spiritual routine.",
    program2Title: "Quran Nazra",
    program2Text:
      "Reading practice for clearer recitation, better fluency, and stronger confidence in daily Quran learning.",
    program3Title: "Para",
    program3Text: "Regular para reading support to improve continuity, accuracy, and habit.",
    program4Title: "Duas and Kalmas",
    program4Text: "Important daily duas and kalmas taught with repetition and understanding.",
    program5Title: "Urdu",
    program5Text:
      "Urdu is included to support language familiarity and help students grow in reading and basic understanding alongside Quran study.",
    methodEyebrow: "How It Works",
    methodTitle: "One class, one calm system, one step at a time.",
    step1Label: "Step 1",
    step1Text: "Choose the morning or evening batch according to your routine.",
    step2Label: "Step 2",
    step2Text: "Start with regular attendance and follow the subject flow of the class.",
    step3Label: "Step 3",
    step3Text: "Build improvement through repetition, correction, and daily consistency.",
    scheduleEyebrow: "Timings",
    scheduleTitle: "Two fixed sessions. Same subjects. Easy to follow.",
    scheduleMorning: "Morning Session",
    scheduleMorningText: "Ideal for students who prefer a daytime study routine.",
    scheduleEvening: "Evening Session",
    scheduleEveningText: "A comfortable option after school and daily home work.",
    scheduleNoteTitle: "Subjects included in both sessions",
    scheduleNoteText: "Quran, Quran Nazra, Para, Duas and Kalmas, and Urdu. The classes are offered online.",
    pillAdmission: "Admission Open",
    pillFamily: "Family Friendly",
    pillOnline: "Online Available",
    faqEyebrow: "Frequently Asked Questions",
    faqTitle: "Quick answers for parents and students.",
    faq1Q: "What subjects are taught in the class?",
    faq1A: "Quran, Quran Nazra, Para, Duas and Kalmas, and Urdu are taught in both sessions.",
    faq2Q: "What are the daily class timings?",
    faq2A: "The morning session runs from 10:00 AM to 10:40 AM and the evening session runs from 4:00 PM to 4:40 PM.",
    faq3Q: "Are online classes available?",
    faq3A: "Yes. The classes are online, making it easy for students and families to join from anywhere.",
    faq4Q: "How can parents contact for admission?",
    faq4A: "Parents can call, send a WhatsApp message, or email directly for admission details and batch selection.",
    contactEyebrow: "Contact Rahmat Quran Classes",
    contactTitle: "Ask about admission, timings, or the right batch for your child.",
    contactText:
      "For a quick response, contact directly by phone or WhatsApp. Email is also available for formal inquiries and details about joining the online classes.",
    contactPhone: "Phone",
    contactPhoneText: "Tap to call directly",
    contactWhatsapp: "WhatsApp",
    contactWhatsappText: "Send an admission message",
    contactEmail: "Email",
    contactEmailText: "For details and inquiries",
    contactLocation: "Location",
    contactLocationText: "Local Quran classes",
    contactFormBtn: "Fill Contact Form",
    contactCallBtn: "Call Now",
    contactWhatsappBtn: "WhatsApp Now",
    contactEmailBtn: "Email Now",
    footer1: "© 2026 Rahmat Quran Classes. All rights reserved.",
    footer2: "All content, design, text, and branding are protected. Unauthorized copying or reuse is prohibited.",
    footer3: "Made by Aahil With ❤️",
  },
  ur: {
    brandTitle: "رحمت قرآن کلاسز",
    brandSubtitle: "ادب اور توجہ کے ساتھ آن لائن قرآن تعلیم",
    navAbout: "تعارف",
    navPrograms: "مضامین",
    navTimings: "اوقات",
    navFaq: "سوالات",
    navContact: "رابطہ",
    heroEyebrow: "بسم الله الرحمن الرحیم",
    heroTitle: "آن لائن قرآن تعلیم نظم، محبت اور روزانہ ترقی کے ساتھ۔",
    heroText:
      "رحمت قرآن کلاسز ایک پرسکون اور باادب جگہ ہے جہاں طلبہ قرآن، قرآن ناظرہ، پارہ، دعائیں اور کلمات، اور اردو ایک بہتر اور حوصلہ افزا انداز میں سیکھتے ہیں۔",
    heroForm: "رابطہ فارم بھریں",
    heroJoin: "کلاس جوائن کریں",
    heroSubjects: "مضامین دیکھیں",
    badgeMorning: "صبح کی کلاس",
    badgeEvening: "شام کی کلاس",
    badgeOnline: "آن لائن کلاسز",
    heroPoint1: "آسان تدریس اور مضبوط روزانہ روٹین",
    heroPoint2: "دونوں سیشن میں ایک ہی مضامین پڑھائے جاتے ہیں",
    heroPoint3: "آن لائن طلبہ اور خاندانوں کے لیے موزوں",
    panelLabel: "داخلہ جاری ہے",
    panelTitle: "پانچ اہم مضامین ایک واضح سیکھنے کے راستے میں۔",
    subject1: "قرآن",
    subject2: "قرآن ناظرہ",
    subject3: "پارہ",
    subject4: "دعائیں اور کلمات",
    subject5: "اردو",
    miniMorning: "صبح",
    miniEvening: "شام",
    miniMode: "طریقہ",
    miniModeValue: "آن لائن کلاسز",
    miniContact: "رابطہ",
    aboutEyebrow: "کلاسز کے بارے میں",
    aboutTitle: "ان خاندانوں کے لیے جو خلوص اور قابل اعتماد آن لائن قرآن کلاسز چاہتے ہیں۔",
    aboutText:
      "رحمت قرآن کلاسز میں روزانہ پابندی، باادب تدریس، اور ایک مضبوط طریقہ کار پر توجہ دی جاتی ہے تاکہ طلبہ سکون کے ساتھ بہتر ہو سکیں۔",
    aboutFeatureTitle: "حقیقی بہتری کے لیے مضبوط روٹین",
    aboutFeatureText:
      "ہر سیشن اس طرح ترتیب دیا گیا ہے کہ طلبہ میں پڑھنے کی عادت، قرآن سے تعلق، اہم دعاؤں اور کلمات کی یاد، اور اعتماد پیدا ہو۔",
    aboutCard1Title: "باادب تدریس",
    aboutCard1Text: "طلبہ کو صبر، اصلاح اور واضح رہنمائی کے ساتھ پڑھایا جاتا ہے۔",
    aboutCard2Title: "مضبوط روٹین",
    aboutCard2Text: "باقاعدہ مشق بچوں کو روزانہ تعلیم سے جوڑے رکھتی ہے۔",
    aboutCard3Title: "آسان طریقہ",
    aboutCard3Text: "سبق اس طرح رکھا جاتا ہے کہ نئے اور کم عمر طلبہ بھی آسانی سے سمجھ سکیں۔",
    aboutCard4Title: "خاندانوں کے لیے موزوں",
    aboutCard4Text: "کلاس کے اوقات گھر، اسکول اور آن لائن روٹین کے مطابق رکھے گئے ہیں۔",
    teacherEyebrow: "استاد کا تعارف",
    teacherTitle: "ناظم صبر، وضاحت اور مضبوط روزانہ روٹین کے ساتھ پڑھاتے ہیں۔",
    teacherText: "یہ تعارف ناظم صاحب کو خاندانوں کے سامنے ایک باوقار اور پیشہ ور انداز میں پیش کرتا ہے۔",
    teacherLabel: "استاد کا نام",
    teacherMainText:
      "ناظم طلبہ کو پرسکون اور توجہ والے انداز میں رہنمائی دیتے ہیں تاکہ وہ آہستہ آہستہ بہتر ہوں اور قرآن تعلیم میں اعتماد پیدا کریں۔",
    teacherCard1Title: "تدریسی انداز",
    teacherCard1Text: "ناظم صبر، واضح رہنمائی، تکرار اور نرم اصلاح کے ذریعے آسان تعلیم دیتے ہیں۔",
    teacherCard2Title: "پڑھائے جانے والے مضامین",
    teacherCard2Text: "قرآن، قرآن ناظرہ، پارہ، دعائیں اور کلمات، اور اردو آسان اور طلبہ دوست انداز میں پڑھائے جاتے ہیں۔",
    teacherCard3Title: "کلاس کا طریقہ",
    teacherCard3Text: "کلاسز میں روزانہ پابندی، پڑھنے میں بہتری، اچھے آداب اور اسلامی تعلیم سے جڑے رہنے پر توجہ دی جاتی ہے۔",
    teacherCard4Title: "خاندانوں کے لیے",
    teacherCard4Text: "ان والدین کے لیے موزوں جو باادب، منظم اور آن لائن کلاس چاہتے ہیں۔",
    stat1Label: "مضامین",
    stat1Text: "قرآن، قرآن ناظرہ، پارہ، دعائیں اور کلمات، اور اردو",
    stat2Label: "روزانہ سیشن",
    stat2Text: "ایک صبح اور ایک شام کا سیشن آن لائن طلبہ کے لیے",
    stat3Label: "کلاس دورانیہ",
    stat3Text: "مرکوز کلاسز ایک آسان اور مناسب وقت کے ساتھ",
    programsEyebrow: "مضامین",
    programsTitle: "سادہ نصاب جو خاندانوں کی اہم ضرورتوں کو پورا کرتا ہے۔",
    program1Title: "قرآن",
    program1Text: "بنیادی قرآن تعلیم جو روزانہ تلاوت، سماعت اور روحانی تعلق کو مضبوط کرتی ہے۔",
    program2Title: "قرآن ناظرہ",
    program2Text: "واضح قراءت، روانی اور اعتماد کے لیے پڑھنے کی مشق۔",
    program3Title: "پارہ",
    program3Text: "پارہ کی باقاعدہ مشق تاکہ تسلسل، درستگی اور عادت بہتر ہو۔",
    program4Title: "دعائیں اور کلمات",
    program4Text: "اہم روزانہ دعائیں اور کلمات تکرار اور سمجھ کے ساتھ سکھائے جاتے ہیں۔",
    program5Title: "اردو",
    program5Text: "اردو شامل ہے تاکہ زبان سے آشنائی اور سمجھ میں بہتری آئے۔",
    methodEyebrow: "طریقہ کار",
    methodTitle: "ایک کلاس، ایک پرسکون نظام، اور قدم بہ قدم تعلیم۔",
    step1Label: "مرحلہ 1",
    step1Text: "اپنی روٹین کے مطابق صبح یا شام کا بیچ منتخب کریں۔",
    step2Label: "مرحلہ 2",
    step2Text: "باقاعدہ حاضری کے ساتھ مضامین کے سلسلے کے مطابق پڑھائی شروع کریں۔",
    step3Label: "مرحلہ 3",
    step3Text: "تکرار، اصلاح اور روزانہ پابندی کے ذریعے بہتری پیدا کریں۔",
    scheduleEyebrow: "اوقات",
    scheduleTitle: "دو مقررہ سیشن، ایک ہی مضامین، آسان نظام۔",
    scheduleMorning: "صبح کا سیشن",
    scheduleMorningText: "ان طلبہ کے لیے جو دن کے وقت پڑھنا پسند کرتے ہیں۔",
    scheduleEvening: "شام کا سیشن",
    scheduleEveningText: "اسکول اور روزانہ کے کام کے بعد مناسب وقت۔",
    scheduleNoteTitle: "دونوں سیشن میں شامل مضامین",
    scheduleNoteText: "قرآن، قرآن ناظرہ، پارہ، دعائیں اور کلمات، اور اردو۔ کلاسز آن لائن فراہم کی جاتی ہیں۔",
    pillAdmission: "داخلہ جاری ہے",
    pillFamily: "خاندانوں کے لیے موزوں",
    pillOnline: "آن لائن دستیاب",
    faqEyebrow: "اکثر پوچھے گئے سوالات",
    faqTitle: "والدین اور طلبہ کے لیے فوری جواب۔",
    faq1Q: "کلاس میں کون سے مضامین پڑھائے جاتے ہیں؟",
    faq1A: "قرآن، قرآن ناظرہ، پارہ، دعائیں اور کلمات، اور اردو دونوں سیشن میں پڑھائے جاتے ہیں۔",
    faq2Q: "روزانہ کلاس کے اوقات کیا ہیں؟",
    faq2A: "صبح کا سیشن 10:00 سے 10:40 اور شام کا سیشن 4:00 سے 4:40 تک ہے۔",
    faq3Q: "کیا آن لائن کلاسز دستیاب ہیں؟",
    faq3A: "جی ہاں، کلاسز آن لائن ہیں اور کہیں سے بھی جوائن کی جا سکتی ہیں۔",
    faq4Q: "داخلے کے لیے والدین کیسے رابطہ کریں؟",
    faq4A: "والدین فون، واٹس ایپ یا ای میل کے ذریعے داخلہ اور بیچ کی تفصیلات کے لیے رابطہ کر سکتے ہیں۔",
    contactEyebrow: "رحمت قرآن کلاسز سے رابطہ کریں",
    contactTitle: "داخلہ، اوقات یا مناسب بیچ کے بارے میں پوچھیں۔",
    contactText:
      "فوری جواب کے لیے فون یا واٹس ایپ پر رابطہ کریں۔ آن لائن کلاسز سے متعلق معلومات کے لیے ای میل بھی دستیاب ہے۔",
    contactPhone: "فون",
    contactPhoneText: "براہ راست کال کریں",
    contactWhatsapp: "واٹس ایپ",
    contactWhatsappText: "داخلہ کے لیے پیغام بھیجیں",
    contactEmail: "ای میل",
    contactEmailText: "تفصیلات اور معلومات کے لیے",
    contactLocation: "مقام",
    contactLocationText: "مقامی قرآن کلاسز",
    contactFormBtn: "رابطہ فارم بھریں",
    contactCallBtn: "ابھی کال کریں",
    contactWhatsappBtn: "ابھی واٹس ایپ کریں",
    contactEmailBtn: "ابھی ای میل کریں",
    footer1: "© 2026 رحمت قرآن کلاسز۔ جملہ حقوق محفوظ ہیں۔",
    footer2: "تمام مواد، ڈیزائن اور برانڈنگ محفوظ ہے۔ بغیر اجازت نقل یا استعمال ممنوع ہے۔",
    footer3: "Aahil کی طرف سے ❤️",
  },
  ar: {
    brandTitle: "فصول رحمت للقرآن",
    brandSubtitle: "تعليم القرآن عبر الإنترنت مع الأدب والعناية",
    navAbout: "حول",
    navPrograms: "البرامج",
    navTimings: "المواعيد",
    navFaq: "الأسئلة",
    navContact: "التواصل",
    heroEyebrow: "بسم الله الرحمن الرحيم",
    heroTitle: "تعليم القرآن عبر الإنترنت بانضباط ودفء وتقدم يومي.",
    heroText:
      "رحمت قرآن کلاسز مكان هادئ ومحترم يتعلم فيه الطلاب القرآن وقرآن ناظرة والباره والأدعية والكلمات والأردية في بيئة مشجعة ومنظمة.",
    heroForm: "املأ نموذج التواصل",
    heroJoin: "انضم إلى الحصة",
    heroSubjects: "عرض المواد",
    badgeMorning: "دفعة صباحية",
    badgeEvening: "دفعة مسائية",
    badgeOnline: "حصص أونلاين",
    heroPoint1: "تعليم بسيط مع روتين يومي قوي",
    heroPoint2: "نفس المواد تُدرّس في كلا الفترتين",
    heroPoint3: "مصمم للطلاب والعائلات عبر الإنترنت",
    panelLabel: "التسجيل مفتوح",
    panelTitle: "خمسة مواد أساسية في مسار تعليمي واضح.",
    subject1: "القرآن",
    subject2: "قرآن ناظرة",
    subject3: "الباره",
    subject4: "الأدعية والكلمات",
    subject5: "الأردية",
    miniMorning: "صباح",
    miniEvening: "مساء",
    miniMode: "النظام",
    miniModeValue: "حصص أونلاين",
    miniContact: "التواصل",
    aboutEyebrow: "عن الحصص",
    aboutTitle: "مناسبة للعائلات التي تريد حصص قرآن صادقة وموثوقة عبر الإنترنت.",
    aboutText:
      "تركز رحمت قرآن کلاسز على الاستمرار اليومي والتعليم المحترم والطريقة الثابتة التي تساعد الطلاب على التحسن براحة ومن دون ضغط.",
    aboutFeatureTitle: "روتين مركز لتحسن حقيقي",
    aboutFeatureText:
      "تم تصميم كل حصة لمساعدة الطلاب على بناء عادة القراءة وتقوية الصلة بالقرآن وحفظ الأدعية والكلمات المهمة وزيادة الثقة.",
    aboutCard1Title: "تعليم محترم",
    aboutCard1Text: "يتم توجيه الطلاب بالصبر والتصحيح والشرح الواضح.",
    aboutCard2Title: "روتين قوي",
    aboutCard2Text: "الممارسة المنتظمة تُبقي الأطفال مرتبطين بالتعلم كل يوم.",
    aboutCard3Title: "طريقة سهلة",
    aboutCard3Text: "تظل الدروس سهلة الفهم حتى للمبتدئين أو الصغار.",
    aboutCard4Title: "مناسبة للعائلات",
    aboutCard4Text: "أوقات الحصص مناسبة للبيت والمدرسة والدراسة عبر الإنترنت.",
    teacherEyebrow: "ملف المعلم",
    teacherTitle: "ناظم يدرّس بالصبر والوضوح وروتين يومي قوي.",
    teacherText: "هذا الملف يعرّف بالعالم ناظم بطريقة محترمة ومهنية للعائلات.",
    teacherLabel: "اسم المعلم",
    teacherMainText:
      "يقود ناظم الطلاب بأسلوب هادئ ومركز يساعدهم على التحسن التدريجي وبناء الثقة والانتظام في تعلم القرآن.",
    teacherCard1Title: "أسلوب التدريس",
    teacherCard1Text: "يدرّس ناظم بالصبر والإرشاد الواضح والتكرار والتصحيح اللطيف.",
    teacherCard2Title: "المواد التي تُدرّس",
    teacherCard2Text: "القرآن وقرآن ناظرة والباره والأدعية والكلمات والأردية تُدرّس بطريقة بسيطة ومناسبة للطلاب.",
    teacherCard3Title: "منهج الحصة",
    teacherCard3Text: "تركز الحصص على الروتين اليومي وتحسين القراءة والآداب والبقاء قريبًا من التعلم الإسلامي.",
    teacherCard4Title: "للعائلات",
    teacherCard4Text: "مناسب للآباء الذين يريدون حصة محترمة ومنظمة عبر الإنترنت.",
    stat1Label: "المواد",
    stat1Text: "القرآن وقرآن ناظرة والباره والأدعية والكلمات والأردية",
    stat2Label: "الحصص اليومية",
    stat2Text: "حصة صباحية وحصة مسائية للمتعلمين عبر الإنترنت",
    stat3Label: "مدة الحصة",
    stat3Text: "حصص مركزة بوقت مناسب ومنظم",
    programsEyebrow: "البرامج",
    programsTitle: "منهج بسيط يغطي ما تهتم به العائلات أكثر.",
    program1Title: "القرآن",
    program1Text: "تعليم أساسي للقرآن يساعد الطلاب على البقاء قريبين من التلاوة اليومية والجانب الروحي.",
    program2Title: "قرآن ناظرة",
    program2Text: "تدريب على القراءة لوضوح التلاوة والطلاقة والثقة.",
    program3Title: "الباره",
    program3Text: "دعم منتظم لقراءة الباره لتحسين الاستمرار والدقة والعادة.",
    program4Title: "الأدعية والكلمات",
    program4Text: "يتم تعليم الأدعية والكلمات اليومية المهمة بالتكرار والفهم.",
    program5Title: "الأردية",
    program5Text: "تم إدراج الأردية لدعم فهم اللغة وتحسين القراءة بجانب دراسة القرآن.",
    methodEyebrow: "كيف يعمل",
    methodTitle: "حصة واحدة ونظام هادئ وخطوة بعد خطوة.",
    step1Label: "الخطوة 1",
    step1Text: "اختر الدفعة الصباحية أو المسائية حسب روتينك.",
    step2Label: "الخطوة 2",
    step2Text: "ابدأ بالانتظام واتبع تسلسل المواد في الحصة.",
    step3Label: "الخطوة 3",
    step3Text: "ابنِ التحسن من خلال التكرار والتصحيح والاستمرار اليومي.",
    scheduleEyebrow: "المواعيد",
    scheduleTitle: "فترتان ثابتتان. نفس المواد. طريقة سهلة.",
    scheduleMorning: "الفترة الصباحية",
    scheduleMorningText: "مناسبة للطلاب الذين يفضلون الدراسة في النهار.",
    scheduleEvening: "الفترة المسائية",
    scheduleEveningText: "خيار مريح بعد المدرسة والأعمال اليومية.",
    scheduleNoteTitle: "المواد المتاحة في الفترتين",
    scheduleNoteText: "القرآن وقرآن ناظرة والباره والأدعية والكلمات والأردية. الحصص متاحة عبر الإنترنت.",
    pillAdmission: "التسجيل مفتوح",
    pillFamily: "مناسبة للعائلات",
    pillOnline: "متاح أونلاين",
    faqEyebrow: "الأسئلة الشائعة",
    faqTitle: "إجابات سريعة للآباء والطلاب.",
    faq1Q: "ما المواد التي تُدرّس في الحصة؟",
    faq1A: "القرآن وقرآن ناظرة والباره والأدعية والكلمات والأردية تُدرّس في كلتا الفترتين.",
    faq2Q: "ما هي أوقات الحصص اليومية؟",
    faq2A: "الفترة الصباحية من 10:00 إلى 10:40، والفترة المسائية من 4:00 إلى 4:40.",
    faq3Q: "هل الحصص أونلاين متاحة؟",
    faq3A: "نعم، الحصص أونلاين مما يسهل على الطلاب والعائلات الانضمام من أي مكان.",
    faq4Q: "كيف يمكن للآباء التواصل من أجل التسجيل؟",
    faq4A: "يمكن للآباء الاتصال أو إرسال واتساب أو بريد إلكتروني لمعرفة التفاصيل واختيار الدفعة.",
    contactEyebrow: "تواصل مع رحمت قرآن کلاسز",
    contactTitle: "اسأل عن التسجيل أو المواعيد أو الدفعة المناسبة لطفلك.",
    contactText: "لرد سريع تواصل عبر الهاتف أو واتساب. البريد الإلكتروني متاح أيضًا للاستفسارات الرسمية عن الحصص الأونلاين.",
    contactPhone: "الهاتف",
    contactPhoneText: "اضغط للاتصال مباشرة",
    contactWhatsapp: "واتساب",
    contactWhatsappText: "أرسل رسالة للتسجيل",
    contactEmail: "البريد الإلكتروني",
    contactEmailText: "للتفاصيل والاستفسارات",
    contactLocation: "الموقع",
    contactLocationText: "حصص قرآن محلية",
    contactFormBtn: "املأ نموذج التواصل",
    contactCallBtn: "اتصل الآن",
    contactWhatsappBtn: "واتساب الآن",
    contactEmailBtn: "راسل الآن",
    footer1: "© 2026 رحمت قرآن کلاسز. جميع الحقوق محفوظة.",
    footer2: "كل المحتوى والتصميم والنصوص والعلامة التجارية محمية. يمنع النسخ أو الاستخدام دون إذن.",
    footer3: "صنعه Aahil ❤️",
  },
};

function applyLanguage(lang) {
  const locale = translations[lang] ? lang : "en";
  const isRtl = locale === "ur" || locale === "ar";

  document.documentElement.lang = locale;
  document.documentElement.dir = isRtl ? "rtl" : "ltr";
  document.body.classList.toggle("rtl", isRtl);

  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const key = element.dataset.i18n;
    if (translations[locale][key]) {
      element.textContent = translations[locale][key];
    }
  });

  langButtons.forEach((button) => {
    button.classList.toggle("is-active", button.dataset.lang === locale);
  });

  localStorage.setItem("rahmat-language", locale);
}

if (menuToggle && siteNav) {
  menuToggle.addEventListener("click", () => {
    siteNav.classList.toggle("is-open");
  });

  siteNav.querySelectorAll("a").forEach((link) => {
    link.addEventListener("click", () => {
      siteNav.classList.remove("is-open");
    });
  });
}

langButtons.forEach((button) => {
  button.addEventListener("click", () => {
    applyLanguage(button.dataset.lang);
  });
});

applyLanguage(localStorage.getItem("rahmat-language") || "en");
